name: Aggregate Outputs and Post Comment

on:
  workflow_run:
    workflows: ["Unit tests", "Next.js Bundle Analysis"]
    types:
      - completed

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Jest Coverage Report
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: unit-tests.yml
          commit: ${{github.event.pull_request.head.sha}}
          name:  jest-coverage-report
          path: .
        continue-on-error: true

      - name: Nextjs Bundle Analysis Report
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: nextjs-bundle-analysis.yml
          commit: ${{github.event.pull_request.head.sha}}
          name: next-bundle-analysis
          path: .
        continue-on-error: true

      - name: Aggregate Outputs
        run: |
          echo "### Consolidated Output" > consolidated_output.txt
           echo "" >> consolidated_output.txt
           if [ -f jest-coverage-report.md ]; then
             echo "#### Jest Coverage Report" >> consolidated_output.txt
             cat jest-coverage-report.md >> consolidated_output.txt
             echo "" >> consolidated_output.txt
           else
             echo "#### Jest Coverage Report not found" >> consolidated_output.txt
           fi
           if [ -f next-bundle-analysis.txt ]; then
             echo "#### Next.js Bundle Analysis Report" >> consolidated_output.txt
             cat next-bundle-analysis.txt >> consolidated_output.txt
             echo "" >> consolidated_output.txt
           else
             echo "#### Next.js Bundle Analysis Report not found" >> consolidated_output.txt
           fi

      - name: Get PR information
        uses: potiuk/get-workflow-origin@v1_6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: Post Consolidated Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ steps.source-run-info.outputs.pullRequestNumber }}
          path: consolidated_output.txt
